/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "Brown-shadow": "#4f4e4d",
        primaryBeige: "#D2BDAE",
        standardBeige: "#B8967E",
        secondaryBeige: "#DCCBC1",
        lightBeige: "#F9F7F5",
        primaryBlack: "#262626",
        primaryWhite: "#FDFCFB",
        secondaryWhite: "#F5F5FA",
        textColor: "#939392",
        primaryNavyBlue: "#090B1E",
        primaryTextColor: "#797979",
      },
      boxShadow: {
        primaryShadow: " 0px 10px 25px 0px rgba(151, 143, 175, 0.04)",
        "side-profileshadow": "rgba(0, 0, 0, 0.2) 0px 10px 20px -10px",
      },
      fontFamily: {
        customBold: ["ArchivoNarrow-Bold", "sans"],
        customBoldItalic: ["ArchivoNarrow-BoldItalic", "sans"],
        customItalic: ["ArchivoNarrow-Italic", "sans"],
        customMedium: ["ArchivoNarrow-Medium", "sans"],
        customMediumItalic: ["ArchivoNarrow-MediumItalic", "sans"],
        customRegular: ["ArchivoNarrow-Regular", "sans"],
        customSemiBold: ["ArchivoNarrow-SemiBold", "sans"],
        customSemiBoldItalic: ["ArchivoNarrow-SemiBoldItalic", "sans"],
        "gogh-black-italic": "Gogh-BlackItalic",
        "gogh-bold": "Gogh-Bold",
        "gogh-bold-italic": "Gogh-BoldItalic",
        "gogh-book": "Gogh-Book",
        "gogh-book-italic": "Gogh-BookItalic",
        "gogh-extra-bold": "Gogh-ExtraBold",
        "gogh-extra-bold-italic": "Gogh-ExtraBoldItalic",
        "gogh-hairline": "Gogh-Hairline",
        "gogh-hairline-italic": "Gogh-HairlineItalic",
        "gogh-heavy": "Gogh-Heavy",
        "gogh-heavy-italic": "Gogh-HeavyItalic",
        "gogh-light": "Gogh-Light",
        "gogh-light-italic": "Gogh-LightItalic",
        "gogh-medium": "Gogh-Medium",
        "gogh-medium-italic": "Gogh-MediumItalic",
        "gogh-regular": "Gogh-Regular",
        "gogh-regular-italic": "Gogh-RegularItalic",
        "gogh-thin": "Gogh-Thin",
        "gogh-thin-italic": "Gogh-ThinItalic",
        "gogh-black": "goghblack",
      },
    },
  },
  plugins: [],
};
